apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-untrusted
  annotations:
    container.apparmor.security.beta.kubernetes.io/ubuntu: unconfined
    io.kubernetes.cri.untrusted-workload: "true"
spec:
  containers:
  - name: ubuntu
    image: ubuntu:xenial
    command: ['sh', '-c', 'sleep 3600']
    securityContext:
      capabilities:
        add: ["SYS_ADMIN"]
    volumeMounts:
      - name: scripts
        mountPath: /tmp/scripts
  volumes:
  - name: scripts
    configMap:
      name: hack