apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    security: trusted
  annotations:
    container.apparmor.security.beta.kubernetes.io/ubuntu: unconfined
spec:
  containers:
  - name: ubuntu
    image: ubuntu:xenial
    command: ['sh', '-c', 'sleep 3600']
    securityContext:
      capabilities:
        add: ["SYS_ADMIN"]
    volumeMounts:
      - name: scripts
        mountPath: /tmp/scripts
  volumes:
  - name: scripts
    configMap:
      name: hack
  nodeSelector:
    option: breakable
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: security
              operator: In
              values:
              - untrusted
          topologyKey: failure-domain.beta.kubernetes.io/host